Embedding:
  Arcane:
    Prompt: arcane style
  Analog:
    Prompt: analog style
Subject:
  Astronaut:
    Prompt: an astronaut riding a horse
  Horse:
    Prompt: a horse riding an astronaut
Details:
  Sunny:
    Prompt: intricate, detailed, sunny
  Cloudy:
    Prompt: cloudy, dark, rainy
Style:
  Art:
    Prompt: painted by a master painter
  Photography:
    Prompt: photographed by a master photographer
Negative:
  Ugly:
    Prompt: ''
    NegPrompt: ugly, disfigured
_settings:
  Euler:
    Setting: 'Steps: 30, Sampler: Euler a, CFG scale: 5, Seed: 1, Size: 512x512, Model
      hash: b172032e, Model: analogProtoSimpBlend'
    SettingName: Euler
